# Generated by Django 6.0.4 on 2026-04-22 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University_register', '0002_alter_course_description_alter_course_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='University_register.professor'),
        ),
    ]
